/**
 * REAL fixture content for canvas tests — the artifact-pipeline fixture
 * set (generated by the actual wireframe skill; see the fixtures README).
 * Imported raw via Vite so the unit suite exercises the same SVG text and
 * spec metadata the real pipeline serves; the integration suite gets the
 * same files through a real server.
 */
import { parse } from "yaml";

import type { ComplianceResponse, ParsedSpecMetadata, VersionSummary } from "@studio/contract";

// Stable {region}__{component}_{idx} ids in assembled/violating fixtures.
export const ASSEMBLED_NODE_IDS = [
  "header__breadcrumb-default_0",
  "main__banner-info_0",
  "main__badge-tag_1",
] as const;

import assembledSvgRaw from "../../../../server/test/artifact-pipeline/fixtures/assembled/wireframe.svg?raw";
import assembledSpecRaw from "../../../../server/test/artifact-pipeline/fixtures/assembled/wireframe.spec.yaml?raw";
import violatingSvgRaw from "../../../../server/test/artifact-pipeline/fixtures/violating/wireframe.svg?raw";
import swissDashboardSvgRaw from "../../../../server/test/artifact-pipeline/fixtures/swiss-dashboard/wireframe.svg?raw";
import scriptInjectionSvgRaw from "../../../../server/test/artifact-pipeline/fixtures/adversarial/script-injection.svg?raw";
import eventHandlersSvgRaw from "../../../../server/test/artifact-pipeline/fixtures/adversarial/event-handlers.svg?raw";
import externalReferencesSvgRaw from "../../../../server/test/artifact-pipeline/fixtures/adversarial/external-references.svg?raw";

export const ASSEMBLED_SVG_TEXT: string = assembledSvgRaw;
export const VIOLATING_SVG_TEXT: string = violatingSvgRaw;
export const SWISS_DASHBOARD_SVG_TEXT: string = swissDashboardSvgRaw;
export const SCRIPT_INJECTION_SVG_TEXT: string = scriptInjectionSvgRaw;
export const EVENT_HANDLERS_SVG_TEXT: string = eventHandlersSvgRaw;
export const EXTERNAL_REFERENCES_SVG_TEXT: string = externalReferencesSvgRaw;

/** The assembled fixture's parsed wireframe.spec.yaml — real metadata. */
export function assembledSpec(): ParsedSpecMetadata {
  return parse(assembledSpecRaw) as ParsedSpecMetadata;
}

/** A VersionSummary in the artifact-pipeline projection shape. */
export function versionSummary(
  number: number,
  overrides: Partial<VersionSummary> = {},
): VersionSummary {
  return {
    number,
    parent: number > 1 ? number - 1 : null,
    tool: "wf_generate",
    brief: `version ${number} of the assembled dashboard`,
    created: `2026-06-10T0${Math.min(number, 9)}:00:00.000Z`,
    compliance: { status: "completed", passed: 7, failed: 0, advisory: 1 },
    ...overrides,
  };
}

/**
 * A ComplianceResponse mirroring the violating fixture's known result:
 * swiss-fixed-type-scale fails and maps to main__banner-info_0.
 */
export function violatingComplianceResponse(): ComplianceResponse {
  return {
    status: "fail",
    passed: 6,
    failed: 1,
    advisory: 1,
    rules: [
      {
        ruleId: "swiss-fixed-type-scale",
        status: "fail",
        message: "font-size 17 is not on the swiss type scale (9/11/13/14/22/32/40)",
        nodeIds: ["main__banner-info_0"],
      },
      {
        ruleId: "swiss-grid-columns",
        status: "pass",
        nodeIds: [],
      },
      {
        ruleId: "swiss-photography-discipline",
        status: "warn",
        message: "document-level advisory without a node mapping",
        nodeIds: [],
      },
    ],
  };
}

/** An all-pass ComplianceResponse for head versions. */
export function passingComplianceResponse(): ComplianceResponse {
  return {
    status: "pass",
    passed: 8,
    failed: 0,
    advisory: 0,
    rules: [
      { ruleId: "swiss-fixed-type-scale", status: "pass", nodeIds: [] },
      { ruleId: "swiss-grid-columns", status: "pass", nodeIds: [] },
    ],
  };
}
