/**
 * Composition helpers for the artifact-pipeline suites — a real workspace
 * store on a temp directory, real fixture content generated by the
 * wireframe skill (see fixtures/README.md), real bridge instances (the
 * design-systems MCP server is never mocked; a deliberately not-started
 * bridge exercises the genuine bridge_down path), and typed event waiting.
 */
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { WorkspaceMeta } from "@studio/contract";

import {
  createArtifactPipeline,
  createPipelineEventBus,
  createStoreVersionFileResolver,
  type ArtifactPipeline,
  type ComplianceBridge,
  type PipelineEventBus,
  type PipelineEventMap,
  type PipelineEventName,
  type PipelineResult,
} from "../../src/artifact-pipeline/index.js";
import { createMcpBridge, type McpBridge } from "../../src/mcp/bridge.js";
import { captureLogger, type CapturedLogger } from "../helpers.js";
import { realBridgeConfig } from "../mcp/mcp-helpers.js";
import { expectOk, makeStore, type StoreFixture } from "../store/store-helpers.js";

export const FIXTURES_DIR = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "fixtures",
);

export const SWISS_DASHBOARD_SVG = path.join(
  FIXTURES_DIR,
  "swiss-dashboard",
  "wireframe.svg",
);
export const SWISS_DASHBOARD_SPEC = path.join(
  FIXTURES_DIR,
  "swiss-dashboard",
  "wireframe.spec.yaml",
);
export const ASSEMBLED_SVG = path.join(
  FIXTURES_DIR,
  "assembled",
  "wireframe.svg",
);
export const ASSEMBLED_SPEC = path.join(
  FIXTURES_DIR,
  "assembled",
  "wireframe.spec.yaml",
);
export const VIOLATING_SVG = path.join(
  FIXTURES_DIR,
  "violating",
  "wireframe.svg",
);

export function fixtureText(absolutePath: string): string {
  return readFileSync(absolutePath, "utf8");
}

export function adversarialFixture(name: string): string {
  return fixtureText(path.join(FIXTURES_DIR, "adversarial", name));
}

export interface PipelineFixture {
  pipeline: ArtifactPipeline;
  events: PipelineEventBus;
  store: StoreFixture;
  workspace: WorkspaceMeta;
  log: CapturedLogger;
}

/**
 * Compose a pipeline over a real temp-directory store and the given
 * bridge. The caller owns the bridge lifecycle.
 */
export async function makePipeline(
  bridge: ComplianceBridge,
): Promise<PipelineFixture> {
  const store = makeStore();
  const log = captureLogger("debug");
  const events = createPipelineEventBus(log.logger);
  const workspace = expectOk(
    await store.store.workspaces.create("Pipeline Test"),
    "workspace create",
  );
  const pipeline = createArtifactPipeline(
    {
      artifacts: store.store.artifacts,
      bridge,
      versionFiles: createStoreVersionFileResolver(store.rootDir),
      events,
    },
    log.logger,
  );
  return { pipeline, events, store, workspace, log };
}

/**
 * A REAL bridge that has never been started: its state machine reports
 * "stopped" and every call resolves bridge_down — the genuine outage
 * seam, no mocks.
 */
export function stoppedBridge(): McpBridge {
  return createMcpBridge(realBridgeConfig(), captureLogger().logger);
}

/** Resolve with the next emission of `event`, or reject after timeoutMs. */
export function onceEvent<E extends PipelineEventName>(
  events: PipelineEventBus,
  event: E,
  timeoutMs = 30_000,
): Promise<PipelineEventMap[E]> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      unsubscribe();
      reject(new Error(`Timed out waiting for pipeline event "${event}"`));
    }, timeoutMs);
    const unsubscribe = events.on(event, (payload) => {
      clearTimeout(timer);
      unsubscribe();
      resolve(payload);
    });
  });
}

/** Unwrap an ok pipeline result or fail the test with the typed error. */
export function expectPipelineOk<T>(
  result: PipelineResult<T>,
  label = "result",
): T {
  if (!result.ok) {
    throw new Error(
      `expected ok ${label}, got ${result.error.code}: ${result.error.message}`,
    );
  }
  return result.value;
}

/** Unwrap a failed pipeline result, asserting the error code. */
export function expectPipelineFail<T>(
  result: PipelineResult<T>,
  code: string,
  label = "result",
): void {
  if (result.ok) {
    throw new Error(`expected failed ${label}, got ok`);
  }
  if (result.error.code !== code) {
    throw new Error(
      `expected ${label} error code "${code}", got "${result.error.code}": ${result.error.message}`,
    );
  }
}
